import { Activity, ArrowRight, Baby, Bot, CalendarClock, CalendarDays, Clock3, HeartPulse, MapPin, Phone, ScanLine, Stethoscope, UserSearch, Waves } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { doctorService, scheduleService } from '../../../services';
import { DoctorCard } from '../../common/DoctorCard';
import { StatePanel } from '../../common/StatePanel';
import styles from './HomeSections.module.css';
const quick=[{icon:CalendarDays,title:'Đặt lịch khám',desc:'Chủ động chọn bác sĩ và giờ khám',to:'/dat-lich'},{icon:UserSearch,title:'Đội ngũ bác sĩ',desc:'Thông tin bác sĩ và chuyên gia tim mạch',to:'/bac-si'},{icon:CalendarClock,title:'Lịch khám',desc:'Tra cứu lịch làm việc và giờ còn trống',to:'/lich-kham'},{icon:Bot,title:'Trợ lý AI',desc:'Hỗ trợ tra cứu thông tin bệnh viện',to:'/tro-ly-ai'}];
const specialtyIcons=[Activity,HeartPulse,Waves,Stethoscope,Baby,ScanLine];
export function HomeSections(){const doctors=useQuery({queryKey:['doctors'],queryFn:()=>doctorService.list()});const specialties=useQuery({queryKey:['specialties'],queryFn:doctorService.specialties});const facilities=useQuery({queryKey:['facilities'],queryFn:scheduleService.facilities});return <>
<section className={styles.quickSection} aria-label="Dịch vụ nhanh"><div className={`container ${styles.quickGrid}`}>{quick.map((item)=><Link key={item.to} to={item.to}><span><item.icon size={24}/></span><div><strong>{item.title}</strong><small>{item.desc}</small></div><ArrowRight size={18}/></Link>)}</div></section>
<section className="section section-soft"><div className="container"><div className={styles.headingRow}><div><p className="section-eyebrow">Chuyên khoa</p><h2 className="section-heading">Chăm sóc tim mạch toàn diện</h2><p className="section-lead">Hệ thống chuyên khoa sâu phối hợp đa ngành, từ phòng ngừa đến can thiệp và phục hồi.</p></div><Link to="/chuyen-khoa">Xem tất cả <ArrowRight size={17}/></Link></div>{specialties.isLoading?<StatePanel kind="loading"/>:<div className={styles.specialtyGrid}>{specialties.data?.map((item,index)=>{const Icon=specialtyIcons[index];return <Link key={item.id} to={`/chuyen-khoa#${item.id}`}><span><Icon size={22}/></span><div><strong>{item.name}</strong><small>{item.description}</small></div><ArrowRight size={16}/></Link>})}</div>}</div></section>
<section className="section"><div className="container"><div className={styles.headingRow}><div><p className="section-eyebrow">Đội ngũ y bác sĩ</p><h2 className="section-heading">Chuyên gia tận tâm, giàu kinh nghiệm</h2></div><Link to="/bac-si">Tìm bác sĩ <ArrowRight size={17}/></Link></div>{doctors.isLoading?<StatePanel kind="loading"/>:<div className={styles.doctorGrid}>{doctors.data?.slice(0,4).map((doctor)=><DoctorCard doctor={doctor} key={doctor.id}/>)}</div>}</div></section>
<section className={styles.journey}><div className="container"><p className="section-eyebrow">Quy trình đơn giản</p><h2>Đặt lịch khám chỉ trong vài phút</h2><div>{['Chọn cơ sở và chuyên khoa','Chọn bác sĩ phù hợp','Chọn ngày giờ còn trống','Nhận xác nhận lịch khám'].map((item,index)=><article key={item}><span>{index+1}</span><strong>{item}</strong></article>)}</div><Link to="/dat-lich">Đặt lịch ngay <ArrowRight size={17}/></Link></div></section>
<section className="section section-soft"><div className="container"><p className="section-eyebrow">Hệ thống cơ sở</p><h2 className="section-heading">Thuận tiện thăm khám tại Hà Nội</h2>{facilities.isLoading?<StatePanel kind="loading"/>:<div className={styles.facilityGrid}>{facilities.data?.map((facility)=><article key={facility.id}><img src={facility.image} alt={facility.name}/><div><span>{facility.shortName}</span><h3>{facility.name}</h3><p><MapPin size={16}/>{facility.address}</p><p><Phone size={16}/>{facility.phone}</p><p><Clock3 size={16}/>{facility.hours}, Thứ 2 – Thứ 7</p><a href="https://maps.google.com" target="_blank" rel="noreferrer">Xem bản đồ</a></div></article>)}</div>}</div></section>
</>}
